### ISSUE TITLE
Erro grave

### ISSUE THREAD

**Issue by SrAnthony** [allanf181/HangmanGame-C-Sharp#1]
Ele travou quando digitei 2 letras :c

**Comment by allanf181** [comment]
Problema seu, eu avisei... :neutral_face:

**Comment by allanf181** [comment]
Vou deixar a conversa aberta, não sou tão mau. :smile:

:octocat:

**Comment by SrAnthony** [comment]
É um problema, se tem que resolver :P

**Comment by allanf181** [comment]
Eu não fiz, só traduzi, olhe o código.
